#pragma once
#include <cstdint>  // uint32_t, uint64_t

/**
 * @brief Defines the different types of sensors in the system.
 *
 * Each sensor type represents a different physical or simulated data source,
 * and determines how telemetry values are generated and interpreted.
 */
enum class SensorType 
{
    Motion,
    Temperature,
    Battery,
    Pressure
};

/**
 * @brief Represents the operational state of a sensor.
 *
 * The state reflects the health and validity of the sensor based on its internal logic and 
 * readings. Each sensor type defines its own rules for transitioning between states.
 */
enum class SensorState
{
    ACTIVE,   // Sensor is operating normally and producing valid readings
    WARNING,  // Sensor is operating outside optimal range 
    ERROR     // Sensor is in a critical failure state and may stop reporting data
};

/**
 * @brief A telemetry packet produced by a sensor and sent to the gateway.
 *
 * This structure represents a single measurement snapshot generated by a sensor.
 * It is transmitted over the network to the gateway for processing, monitoring,
 * and system-wide state tracking.
 */
struct SensorReading 
{
    uint32_t sensorId;      // The sensor unique identifier
    SensorType type;        // Type of sensor that generated the reading
    SensorState state;      // The state of the sensor
    double value;           // Measured value produced by the sensor
    uint64_t timestamp_ms;  // Time at which the reading was generated (Unix time or milliseconds)
};