#pragma once
#include "common/ProtocolTypes.hpp"

/**
 * @brief Base class representing a generic sensor in the system.
 *
 * A Sensor is responsible for managing its internal lifecycle, generating
 * domain-specific readings, maintaining its operational state, and producing
 * telemetry data that can be transmitted to the gateway.
 */
class Sensor
{
protected:
    SensorReading currentReading;  // Latest sensor reading generated by the sensor
    SensorState currentState;      // Current operational state of the sensor
    uint64_t lastHeartbeatTime;    // Timestamp of the last heartbeat signal sent by the sensor

public:
    /**
     * @brief Constructs a Sensor with default initialization.
     */
    Sensor() = default;

    /**
     * @brief Virtual destructor to ensure proper cleanup of derived classes.
     */
    virtual ~Sensor() = default;

    /**
     * @brief Generates a sensor reading based on the specific sensor type.
     *
     * Each derived class implements its own logic for producing sensor data.
     */
    virtual SensorReading generateReading() = 0;

    /**
     * @brief Updates the internal state of the sensor.
     *
     * @param state New state of the sensor
     */
    void updateState(SensorState state);

    /**
     * @brief Main execution loop of the sensor.
     *
     * Handles periodic reading generation, state updates, and heartbeat logic.
     */
    void runLoop();

    /**
     * @brief Creates a telemetry packet from the current sensor reading.
     *
     * @return SensorReading structured telemetry data
     */
    SensorReading createTelemetry() const;
};