#pragma once
#include "common/ProtocolTypes.hpp"

/**
 * @brief Base class representing a generic sensor in the system.
 *
 * A Sensor is responsible for managing its internal lifecycle, generating
 * domain-specific readings, maintaining its operational state, and producing
 * telemetry data that can be transmitted to the gateway.
 */
class Sensor
{
protected:
    uint32_t sensorId;             // The sensor unique identifier 
    SensorReading currentReading;  // Latest telemetry packet generated by the sensor
    SensorState currentState;      // Current operational state of the sensor
    uint64_t lastHeartbeatTime;    // Timestamp of the last heartbeat signal sent by the sensor
    double currentValue = 0.0;     // The current value of the sensor

public:
    /**
     * @brief Constructs a sensor with a unique identifier
     * 
     * @param id The sensor id
     */
    Sensor(uint32_t id);

    /**
     * @brief Virtual destructor to ensure proper cleanup of derived classes.
     */
    virtual ~Sensor() = default;

    /**
     * @brief Collects a new measurement from the sensor.
     *
     * Derived classes implement their own logic for generating or acquiring
     * sensor-specific data and updating the sensor state accordingly.
     *
     * @return The measured sensor value.
     */
    virtual double collectData() = 0;

    /**
     * @brief Returns the specific sensor type.
     *
     * Each derived class defines its own sensor type identifier used in telemetry packets.
     */
    virtual SensorType getType() const = 0;

    /**
     * @brief Updates the internal state of the sensor.
     *
     * @param state New state of the sensor
     */
    void updateState(SensorState state);

    /**
     * @brief Creates a telemetry packet from the current sensor reading.
     *
     * @return SensorReading structured telemetry data
     */
    SensorReading createTelemetry();
};